### PR TITLE
fix(bar): Fix BarItemProps types

### LINKED ISSUE #1155: Need for casting types over an over again in barComponent callback (TS)
**Describe/explain the bug**
I am working on adding tooltip functionality to my custom barComponent (in TypeScript).
I realized that `showTooltip`, `onMouseEnter`, `onMouseLeave` and others won’t accept the event parameter with type
 
`React.MouseEvent<SVGRectElement, MouseEvent>`  

because I think `BarMouseEventHandler` is a generic type with a default value `HTMLCanvasElement` but the generic type was not passed down at `onMouseEnter: BarMouseEventHandler` in `BarItemProps` - `BarItemProps` is not even generic so I can pass it in manually - right here:
 https://github.com/plouc/nivo/blob/52c1bc155b58c522c8dc3ca3d43385630b0c563c/packages/bar/index.d.ts#L54-L87

Also, this is `showTooltip` event is hardcoded: https://github.com/plouc/nivo/blob/52c1bc155b58c522c8dc3ca3d43385630b0c563c/packages/bar/index.d.ts#L83

And that causes to write this kind of code in TypeScript where I need to cast the types over and over again:
```
const handleMouseEnter = (
    e: React.MouseEvent<SVGRectElement, MouseEvent>,
  ) => {
    onMouseEnter(
      data as BarExtendedDatum,
      (e as unknown) as React.MouseEvent<HTMLCanvasElement, MouseEvent>,
    )
    if (tooltip) {
      showTooltip(
        tooltip(data as BarExtendedDatum),
        (e as unknown) as React.MouseEvent<HTMLCanvasElement, MouseEvent>,
      )
    }
  }
```

As you see I also need to type cast the data, since the callback functions are expecting (and what actually provided `data` prop is) `BarExtendedDatum`, however the provided `data` props is typed as:
```
var data: {
    id: string | number;
    value: number;
    indexValue: string | number;
}
```

**To Reproduce**
Check out the sandbox and try deleting types in `char-enhancers.tsx` to observe the errors.
https://codesandbox.io/s/horizontal-bar-chart-xuuy9?file=/src/chart-enhancers.tsx

### PR DESCRIPTION
**Pull request by eggei**
Fixes #1155 

**Changes:**

- Change `data` prop type to `BarExtendedDatum`
- Remove `color` field in `data` prop's type - it doesn't exist in `data` prop
- Create `BarTooltipDatum` to pass `color` type to tooltip props along with
  `BarExtendedDatum`
- Add `SVGRectElement` to `BarMouseEventHandler` generic type
- Update deprecated `React.StatelessComponent` to `React.FC`

### CODE REVIEW

**Comment by eggei** [comment]
Hit @wyze - I created this PR after our conversation on the Discord channel.  I can't request reviews for some reason, so I thought I can mention you here to let you know about this. Thank you!

File: packages/swarmplot/index.d.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ declare module '@nivo/swarmplot' {
         Axes = 'axes',
         Nodes = 'nodes',
         Mesh = 'mesh',
-        Annotations = 'annotations'
+        Annotations = 'annotations',
```
Comment (eggei) [inline packages/swarmplot/index.d.ts:50]: This got fixed by the linter checks, so I let it in with my comment.

Comment (wyze) [reply packages/swarmplot/index.d.ts:50]: Thanks, I think this is what is failing the build.

File: packages/bar/index.d.ts [hunk 2]
```diff
@@ -153,7 +151,6 @@ declare module '@nivo/bar' {
             onClick: BarMouseEventHandler<SVGRectElement>
             onMouseEnter: BarMouseEventHandler<SVGRectElement>
             onMouseLeave: BarMouseEventHandler<SVGRectElement>
-            role: string
```
Comment (wyze) [inline packages/bar/index.d.ts:156]: I think you need to revert this deletion, but everything else looks good.

**Review by wyze — CHANGES_REQUESTED** [review]

File: packages/bar/index.d.ts (hunk 2 above)
Comment (eggei) [reply packages/bar/index.d.ts:156]: Hmm, this might be my first accidental deletion. + I committed it 😅 shameful.
I am sorry for that, thanks for reviewing - I will resolve this soon

Comment (wyze) [reply packages/bar/index.d.ts:156]: No worries and no need to apologize! 😀

**Review by wyze — APPROVED** [review]

**Comment by wyze** [comment]
Thanks!
